# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userPreferencesWidget.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

from views.light_custom_pallet import LightCustomPalette


class Ui_NewUserPreferencesWidget(object):

    def __init__(self, db, username, age, gender, occupation):
        self.db = db
        self.username = username
        self.age = age
        self.gender = gender
        self.occupation = occupation
        self.user_id = len(self.db.users_dic) + 1

    def setupUi(self, NewUserPreferencesWidget):
        NewUserPreferencesWidget.setObjectName("NewUserPreferencesWidget")
        NewUserPreferencesWidget.resize(600, 400)
        self.palette = LightCustomPalette()
        NewUserPreferencesWidget.setPalette(self.palette.palette)
        self.verticalLayout = QtWidgets.QVBoxLayout(NewUserPreferencesWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(NewUserPreferencesWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 25))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.scrollArea = QtWidgets.QScrollArea(NewUserPreferencesWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 566, 1119))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.actionLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionLabel.sizePolicy().hasHeightForWidth())
        self.actionLabel.setSizePolicy(sizePolicy)
        self.actionLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.actionLabel.setObjectName("actionLabel")
        self.verticalLayout_2.addWidget(self.actionLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.actionSlider = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionSlider.sizePolicy().hasHeightForWidth())
        self.actionSlider.setSizePolicy(sizePolicy)
        self.actionSlider.setMinimumSize(QtCore.QSize(350, 0))
        self.actionSlider.setMaximum(10)
        self.actionSlider.setSingleStep(1)
        self.actionSlider.setOrientation(QtCore.Qt.Horizontal)
        self.actionSlider.setObjectName("actionSlider")
        self.horizontalLayout_2.addWidget(self.actionSlider)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.actionValue = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.actionValue.setObjectName("actionValue")
        self.horizontalLayout_2.addWidget(self.actionValue)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_20.addLayout(self.verticalLayout_2)
        self.line_17 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.verticalLayout_20.addWidget(self.line_17)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, 10, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.adventureLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adventureLabel.sizePolicy().hasHeightForWidth())
        self.adventureLabel.setSizePolicy(sizePolicy)
        self.adventureLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.adventureLabel.setObjectName("adventureLabel")
        self.verticalLayout_3.addWidget(self.adventureLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.adventureSlider = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adventureSlider.sizePolicy().hasHeightForWidth())
        self.adventureSlider.setSizePolicy(sizePolicy)
        self.adventureSlider.setMinimumSize(QtCore.QSize(350, 0))
        self.adventureSlider.setMaximum(10)
        self.adventureSlider.setSingleStep(1)
        self.adventureSlider.setOrientation(QtCore.Qt.Horizontal)
        self.adventureSlider.setObjectName("adventureSlider")
        self.horizontalLayout_3.addWidget(self.adventureSlider)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.adventureValue = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.adventureValue.setObjectName("adventureValue")
        self.horizontalLayout_3.addWidget(self.adventureValue)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_20.addLayout(self.verticalLayout_3)
        self.line_16 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.verticalLayout_20.addWidget(self.line_16)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.animationLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.animationLabel.sizePolicy().hasHeightForWidth())
        self.animationLabel.setSizePolicy(sizePolicy)
        self.animationLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.animationLabel.setObjectName("animationLabel")
        self.verticalLayout_4.addWidget(self.animationLabel)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.animationSlider = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.animationSlider.sizePolicy().hasHeightForWidth())
        self.animationSlider.setSizePolicy(sizePolicy)
        self.animationSlider.setMinimumSize(QtCore.QSize(350, 0))
        self.animationSlider.setMaximum(10)
        self.animationSlider.setSingleStep(1)
        self.animationSlider.setOrientation(QtCore.Qt.Horizontal)
        self.animationSlider.setObjectName("animationSlider")
        self.horizontalLayout_4.addWidget(self.animationSlider)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.animationValue = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.animationValue.setObjectName("animationValue")
        self.horizontalLayout_4.addWidget(self.animationValue)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_20.addLayout(self.verticalLayout_4)
        self.line_15 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.verticalLayout_20.addWidget(self.line_15)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.childrensLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.childrensLabel.sizePolicy().hasHeightForWidth())
        self.childrensLabel.setSizePolicy(sizePolicy)
        self.childrensLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.childrensLabel.setObjectName("childrensLabel")
        self.verticalLayout_6.addWidget(self.childrensLabel)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.childrensSlider = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.childrensSlider.sizePolicy().hasHeightForWidth())
        self.childrensSlider.setSizePolicy(sizePolicy)
        self.childrensSlider.setMinimumSize(QtCore.QSize(350, 0))
        self.childrensSlider.setMaximum(10)
        self.childrensSlider.setSingleStep(1)
        self.childrensSlider.setOrientation(QtCore.Qt.Horizontal)
        self.childrensSlider.setObjectName("childrensSlider")
        self.horizontalLayout_6.addWidget(self.childrensSlider)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.childrensValue = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.childrensValue.setObjectName("childrensValue")
        self.horizontalLayout_6.addWidget(self.childrensValue)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.verticalLayout_20.addLayout(self.verticalLayout_6)
        self.line_14 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.verticalLayout_20.addWidget(self.line_14)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.comedyLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comedyLabel.sizePolicy().hasHeightForWidth())
        self.comedyLabel.setSizePolicy(sizePolicy)
        self.comedyLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.comedyLabel.setObjectName("comedyLabel")
        self.verticalLayout_5.addWidget(self.comedyLabel)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.comedySlider = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comedySlider.sizePolicy().hasHeightForWidth())
        self.comedySlider.setSizePolicy(sizePolicy)
        self.comedySlider.setMinimumSize(QtCore.QSize(350, 0))
        self.comedySlider.setAutoFillBackground(False)
        self.comedySlider.setMaximum(10)
        self.comedySlider.setSingleStep(1)
        self.comedySlider.setTracking(True)
        self.comedySlider.setOrientation(QtCore.Qt.Horizontal)
        self.comedySlider.setInvertedAppearance(False)
        self.comedySlider.setInvertedControls(False)
        self.comedySlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.comedySlider.setObjectName("comedySlider")
        self.horizontalLayout_5.addWidget(self.comedySlider)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.comedyValue = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.comedyValue.setObjectName("comedyValue")
        self.horizontalLayout_5.addWidget(self.comedyValue)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_20.addLayout(self.verticalLayout_5)
        self.line_13 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.verticalLayout_20.addWidget(self.line_13)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.crimeLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crimeLabel.sizePolicy().hasHeightForWidth())
        self.crimeLabel.setSizePolicy(sizePolicy)
        self.crimeLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.crimeLabel.setObjectName("crimeLabel")
        self.verticalLayout_7.addWidget(self.crimeLabel)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.crimeSlider = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crimeSlider.sizePolicy().hasHeightForWidth())
        self.crimeSlider.setSizePolicy(sizePolicy)
        self.crimeSlider.setMinimumSize(QtCore.QSize(350, 0))
        self.crimeSlider.setMaximum(10)
        self.crimeSlider.setSingleStep(1)
        self.crimeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.crimeSlider.setObjectName("crimeSlider")
        self.horizontalLayout_7.addWidget(self.crimeSlider)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.crimeValue = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.crimeValue.setObjectName("crimeValue")
        self.horizontalLayout_7.addWidget(self.crimeValue)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.verticalLayout_20.addLayout(self.verticalLayout_7)
        self.line_12 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout_20.addWidget(self.line_12)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.documentaryLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.documentaryLabel.sizePolicy().hasHeightForWidth())
        self.documentaryLabel.setSizePolicy(sizePolicy)
        self.documentaryLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.documentaryLabel.setObjectName("documentaryLabel")
        self.verticalLayout_8.addWidget(self.documentaryLabel)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.documentarySlider = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.documentarySlider.sizePolicy().hasHeightForWidth())
        self.documentarySlider.setSizePolicy(sizePolicy)
        self.documentarySlider.setMinimumSize(QtCore.QSize(350, 0))
        self.documentarySlider.setMaximum(10)
        self.documentarySlider.setSingleStep(1)
        self.documentarySlider.setOrientation(QtCore.Qt.Horizontal)
        self.documentarySlider.setObjectName("documentarySlider")
        self.horizontalLayout_8.addWidget(self.documentarySlider)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.documentaryValue = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.documentaryValue.setObjectName("documentaryValue")
        self.horizontalLayout_8.addWidget(self.documentaryValue)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.verticalLayout_20.addLayout(self.verticalLayout_8)
        self.line_11 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_20.addWidget(self.line_11)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.dramaLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dramaLabel.sizePolicy().hasHeightForWidth())
        self.dramaLabel.setSizePolicy(sizePolicy)
        self.dramaLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.dramaLabel.setObjectName("dramaLabel")
        self.verticalLayout_9.addWidget(self.dramaLabel)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.dramaSlider = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dramaSlider.sizePolicy().hasHeightForWidth())
        self.dramaSlider.setSizePolicy(sizePolicy)
        self.dramaSlider.setMinimumSize(QtCore.QSize(350, 0))
        self.dramaSlider.setMaximum(10)
        self.dramaSlider.setSingleStep(1)
        self.dramaSlider.setOrientation(QtCore.Qt.Horizontal)
        self.dramaSlider.setObjectName("dramaSlider")
        self.horizontalLayout_9.addWidget(self.dramaSlider)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.dramaValue = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.dramaValue.setObjectName("dramaValue")
        self.horizontalLayout_9.addWidget(self.dramaValue)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.verticalLayout_20.addLayout(self.verticalLayout_9)
        self.line_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_20.addWidget(self.line_10)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.fantasyLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fantasyLabel.sizePolicy().hasHeightForWidth())
        self.fantasyLabel.setSizePolicy(sizePolicy)
        self.fantasyLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.fantasyLabel.setObjectName("fantasyLabel")
        self.verticalLayout_14.addWidget(self.fantasyLabel)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.fantasySlider = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fantasySlider.sizePolicy().hasHeightForWidth())
        self.fantasySlider.setSizePolicy(sizePolicy)
        self.fantasySlider.setMinimumSize(QtCore.QSize(350, 0))
        self.fantasySlider.setMaximum(10)
        self.fantasySlider.setSingleStep(1)
        self.fantasySlider.setOrientation(QtCore.Qt.Horizontal)
        self.fantasySlider.setObjectName("fantasySlider")
        self.horizontalLayout_14.addWidget(self.fantasySlider)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem8)
        self.fantasyValue = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fantasyValue.setObjectName("fantasyValue")
        self.horizontalLayout_14.addWidget(self.fantasyValue)
        self.verticalLayout_14.addLayout(self.horizontalLayout_14)
        self.verticalLayout_20.addLayout(self.verticalLayout_14)
        self.line_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_20.addWidget(self.line_9)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.filmnoirLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filmnoirLabel.sizePolicy().hasHeightForWidth())
        self.filmnoirLabel.setSizePolicy(sizePolicy)
        self.filmnoirLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.filmnoirLabel.setObjectName("filmnoirLabel")
        self.verticalLayout_13.addWidget(self.filmnoirLabel)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.filmnoirSlider = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filmnoirSlider.sizePolicy().hasHeightForWidth())
        self.filmnoirSlider.setSizePolicy(sizePolicy)
        self.filmnoirSlider.setMinimumSize(QtCore.QSize(350, 0))
        self.filmnoirSlider.setMaximum(10)
        self.filmnoirSlider.setSingleStep(1)
        self.filmnoirSlider.setOrientation(QtCore.Qt.Horizontal)
        self.filmnoirSlider.setObjectName("filmnoirSlider")
        self.horizontalLayout_13.addWidget(self.filmnoirSlider)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem9)
        self.filmnoirValue = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.filmnoirValue.setObjectName("filmnoirValue")
        self.horizontalLayout_13.addWidget(self.filmnoirValue)
        self.verticalLayout_13.addLayout(self.horizontalLayout_13)
        self.verticalLayout_20.addLayout(self.verticalLayout_13)
        self.line_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_20.addWidget(self.line_8)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horrorLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horrorLabel.sizePolicy().hasHeightForWidth())
        self.horrorLabel.setSizePolicy(sizePolicy)
        self.horrorLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.horrorLabel.setObjectName("horrorLabel")
        self.verticalLayout_12.addWidget(self.horrorLabel)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horrorSlider = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horrorSlider.sizePolicy().hasHeightForWidth())
        self.horrorSlider.setSizePolicy(sizePolicy)
        self.horrorSlider.setMinimumSize(QtCore.QSize(350, 0))
        self.horrorSlider.setMaximum(10)
        self.horrorSlider.setSingleStep(1)
        self.horrorSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horrorSlider.setObjectName("horrorSlider")
        self.horizontalLayout_12.addWidget(self.horrorSlider)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem10)
        self.horrorValue = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.horrorValue.setObjectName("horrorValue")
        self.horizontalLayout_12.addWidget(self.horrorValue)
        self.verticalLayout_12.addLayout(self.horizontalLayout_12)
        self.verticalLayout_20.addLayout(self.verticalLayout_12)
        self.line_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_20.addWidget(self.line_7)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.musicalLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.musicalLabel.sizePolicy().hasHeightForWidth())
        self.musicalLabel.setSizePolicy(sizePolicy)
        self.musicalLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.musicalLabel.setObjectName("musicalLabel")
        self.verticalLayout_11.addWidget(self.musicalLabel)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.musicalSlider = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.musicalSlider.sizePolicy().hasHeightForWidth())
        self.musicalSlider.setSizePolicy(sizePolicy)
        self.musicalSlider.setMinimumSize(QtCore.QSize(350, 0))
        self.musicalSlider.setMaximum(10)
        self.musicalSlider.setSingleStep(1)
        self.musicalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.musicalSlider.setObjectName("musicalSlider")
        self.horizontalLayout_11.addWidget(self.musicalSlider)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem11)
        self.musicalValue = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.musicalValue.setObjectName("musicalValue")
        self.horizontalLayout_11.addWidget(self.musicalValue)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        self.verticalLayout_20.addLayout(self.verticalLayout_11)
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_20.addWidget(self.line_6)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.mysteryLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mysteryLabel.sizePolicy().hasHeightForWidth())
        self.mysteryLabel.setSizePolicy(sizePolicy)
        self.mysteryLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.mysteryLabel.setObjectName("mysteryLabel")
        self.verticalLayout_10.addWidget(self.mysteryLabel)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.mysterySlider = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mysterySlider.sizePolicy().hasHeightForWidth())
        self.mysterySlider.setSizePolicy(sizePolicy)
        self.mysterySlider.setMinimumSize(QtCore.QSize(350, 0))
        self.mysterySlider.setMaximum(10)
        self.mysterySlider.setSingleStep(1)
        self.mysterySlider.setOrientation(QtCore.Qt.Horizontal)
        self.mysterySlider.setObjectName("mysterySlider")
        self.horizontalLayout_10.addWidget(self.mysterySlider)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem12)
        self.mysteryValue = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.mysteryValue.setObjectName("mysteryValue")
        self.horizontalLayout_10.addWidget(self.mysteryValue)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        self.verticalLayout_20.addLayout(self.verticalLayout_10)
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_20.addWidget(self.line_5)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.romanceLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.romanceLabel.sizePolicy().hasHeightForWidth())
        self.romanceLabel.setSizePolicy(sizePolicy)
        self.romanceLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.romanceLabel.setObjectName("romanceLabel")
        self.verticalLayout_19.addWidget(self.romanceLabel)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.romanceSlider = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.romanceSlider.sizePolicy().hasHeightForWidth())
        self.romanceSlider.setSizePolicy(sizePolicy)
        self.romanceSlider.setMinimumSize(QtCore.QSize(350, 0))
        self.romanceSlider.setMaximum(10)
        self.romanceSlider.setSingleStep(1)
        self.romanceSlider.setOrientation(QtCore.Qt.Horizontal)
        self.romanceSlider.setObjectName("romanceSlider")
        self.horizontalLayout_19.addWidget(self.romanceSlider)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem13)
        self.romanceValue = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.romanceValue.setObjectName("romanceValue")
        self.horizontalLayout_19.addWidget(self.romanceValue)
        self.verticalLayout_19.addLayout(self.horizontalLayout_19)
        self.verticalLayout_20.addLayout(self.verticalLayout_19)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_20.addWidget(self.line_4)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.scifiLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scifiLabel.sizePolicy().hasHeightForWidth())
        self.scifiLabel.setSizePolicy(sizePolicy)
        self.scifiLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.scifiLabel.setObjectName("scifiLabel")
        self.verticalLayout_18.addWidget(self.scifiLabel)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.scifiSlider = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scifiSlider.sizePolicy().hasHeightForWidth())
        self.scifiSlider.setSizePolicy(sizePolicy)
        self.scifiSlider.setMinimumSize(QtCore.QSize(350, 0))
        self.scifiSlider.setMaximum(10)
        self.scifiSlider.setSingleStep(1)
        self.scifiSlider.setOrientation(QtCore.Qt.Horizontal)
        self.scifiSlider.setObjectName("scifiSlider")
        self.horizontalLayout_18.addWidget(self.scifiSlider)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem14)
        self.scifiValue = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.scifiValue.setObjectName("scifiValue")
        self.horizontalLayout_18.addWidget(self.scifiValue)
        self.verticalLayout_18.addLayout(self.horizontalLayout_18)
        self.verticalLayout_20.addLayout(self.verticalLayout_18)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_20.addWidget(self.line_3)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.thrillerLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thrillerLabel.sizePolicy().hasHeightForWidth())
        self.thrillerLabel.setSizePolicy(sizePolicy)
        self.thrillerLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.thrillerLabel.setObjectName("thrillerLabel")
        self.verticalLayout_17.addWidget(self.thrillerLabel)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.thrillerSlider = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thrillerSlider.sizePolicy().hasHeightForWidth())
        self.thrillerSlider.setSizePolicy(sizePolicy)
        self.thrillerSlider.setMinimumSize(QtCore.QSize(350, 0))
        self.thrillerSlider.setMaximum(10)
        self.thrillerSlider.setSingleStep(1)
        self.thrillerSlider.setOrientation(QtCore.Qt.Horizontal)
        self.thrillerSlider.setObjectName("thrillerSlider")
        self.horizontalLayout_17.addWidget(self.thrillerSlider)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem15)
        self.thrillerValue = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.thrillerValue.setObjectName("thrillerValue")
        self.horizontalLayout_17.addWidget(self.thrillerValue)
        self.verticalLayout_17.addLayout(self.horizontalLayout_17)
        self.verticalLayout_20.addLayout(self.verticalLayout_17)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_20.addWidget(self.line_2)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.warLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.warLabel.sizePolicy().hasHeightForWidth())
        self.warLabel.setSizePolicy(sizePolicy)
        self.warLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.warLabel.setObjectName("warLabel")
        self.verticalLayout_16.addWidget(self.warLabel)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.warSlider = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.warSlider.sizePolicy().hasHeightForWidth())
        self.warSlider.setSizePolicy(sizePolicy)
        self.warSlider.setMinimumSize(QtCore.QSize(350, 0))
        self.warSlider.setMaximum(10)
        self.warSlider.setSingleStep(1)
        self.warSlider.setOrientation(QtCore.Qt.Horizontal)
        self.warSlider.setObjectName("warSlider")
        self.horizontalLayout_16.addWidget(self.warSlider)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem16)
        self.warValue = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.warValue.setObjectName("warValue")
        self.horizontalLayout_16.addWidget(self.warValue)
        self.verticalLayout_16.addLayout(self.horizontalLayout_16)
        self.verticalLayout_20.addLayout(self.verticalLayout_16)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_20.addWidget(self.line)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.westernLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.westernLabel.sizePolicy().hasHeightForWidth())
        self.westernLabel.setSizePolicy(sizePolicy)
        self.westernLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.westernLabel.setObjectName("westernLabel")
        self.verticalLayout_15.addWidget(self.westernLabel)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.westernSlider = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.westernSlider.sizePolicy().hasHeightForWidth())
        self.westernSlider.setSizePolicy(sizePolicy)
        self.westernSlider.setMinimumSize(QtCore.QSize(350, 0))
        self.westernSlider.setMaximum(10)
        self.westernSlider.setSingleStep(1)
        self.westernSlider.setOrientation(QtCore.Qt.Horizontal)
        self.westernSlider.setObjectName("westernSlider")
        self.horizontalLayout_15.addWidget(self.westernSlider)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem17)
        self.westernValue = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.westernValue.setObjectName("westernValue")
        self.horizontalLayout_15.addWidget(self.westernValue)
        self.verticalLayout_15.addLayout(self.horizontalLayout_15)
        self.verticalLayout_20.addLayout(self.verticalLayout_15)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(NewUserPreferencesWidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.sliders = [self.actionSlider, self.adventureSlider, self.animationSlider, self.childrensSlider,
                        self.comedySlider, self.crimeSlider, self.documentarySlider, self.dramaSlider,
                        self.fantasySlider, self.filmnoirSlider, self.horrorSlider, self.musicalSlider,
                        self.mysterySlider, self.romanceSlider, self.scifiSlider, self.thrillerSlider,
                        self.warSlider, self.westernSlider]

        self.retranslateUi(NewUserPreferencesWidget)
        QtCore.QMetaObject.connectSlotsByName(NewUserPreferencesWidget)

        self.buttonBox.accepted.connect(lambda: self.ok_button_clicked(NewUserPreferencesWidget))
        self.buttonBox.rejected.connect(lambda: self.cancel_button_clicked(NewUserPreferencesWidget))

        # connect slider values and labels
        self.actionSlider.valueChanged.connect(lambda: self.update_label(self.actionSlider, self.actionValue))
        self.adventureSlider.valueChanged.connect(lambda: self.update_label(self.adventureSlider, self.adventureValue))
        self.animationSlider.valueChanged.connect(lambda: self.update_label(self.animationSlider, self.animationValue))
        self.childrensSlider.valueChanged.connect(lambda: self.update_label(self.childrensSlider, self.childrensValue))
        self.comedySlider.valueChanged.connect(lambda: self.update_label(self.comedySlider, self.comedyValue))
        self.crimeSlider.valueChanged.connect(lambda: self.update_label(self.crimeSlider, self.crimeValue))
        self.documentarySlider.valueChanged.connect(lambda: self.update_label(self.documentarySlider, self.documentaryValue))
        self.dramaSlider.valueChanged.connect(lambda: self.update_label(self.dramaSlider, self.dramaValue))
        self.fantasySlider.valueChanged.connect(lambda: self.update_label(self.fantasySlider, self.fantasyValue))
        self.filmnoirSlider.valueChanged.connect(lambda: self.update_label(self.filmnoirSlider, self.filmnoirValue))
        self.horrorSlider.valueChanged.connect(lambda: self.update_label(self.horrorSlider, self.horrorValue))
        self.musicalSlider.valueChanged.connect(lambda: self.update_label(self.musicalSlider, self.musicalValue))
        self.mysterySlider.valueChanged.connect(lambda: self.update_label(self.mysterySlider, self.mysteryValue))
        self.romanceSlider.valueChanged.connect(lambda: self.update_label(self.romanceSlider, self.romanceValue))
        self.scifiSlider.valueChanged.connect(lambda: self.update_label(self.scifiSlider, self.scifiValue))
        self.thrillerSlider.valueChanged.connect(lambda: self.update_label(self.thrillerSlider, self.thrillerValue))
        self.warSlider.valueChanged.connect(lambda: self.update_label(self.warSlider, self.warValue))
        self.westernSlider.valueChanged.connect(lambda: self.update_label(self.westernSlider, self.westernValue))

    def update_label(self, slider, label):
        value = slider.value()
        label.setText(str(value))

    def ok_button_clicked(self, NewUserPreferencesWidget):
        info = ""
        preferences = [0.0]
        for slider in self.sliders:

            name = slider.objectName()
            parts = name.split("Slider")
            genre = parts[0].title()

            if genre == "Childrens":
                genre = "Children's"
            elif genre == "Filmnoir":
                genre = "Film-Noir"
            elif genre == "Scifi":
                genre = "Sci-Fi"

            value = slider.value()
            preferences.append(value*10)
            if value > 0:
                if genre != "Documentary":
                    info += genre + "\t\t" + str(value) + "\n"
                else:
                    info += genre + "\t" + str(value) + "\n"

        msg = QMessageBox()
        msg.setWindowTitle("User preferences")
        msg.setIcon(QMessageBox.Question)
        if self.username != "":
            msg.setText("Save this preferences for user {}?".format(self.username))
        else:
            msg.setText("Save this preferences for user {}?".format(self.user_id))

        msg.setInformativeText(info)
        msg.setStandardButtons(QMessageBox.No | QMessageBox.Yes)
        msg.setDefaultButton(QMessageBox.No)

        res = msg.exec_()
        if res == QMessageBox.Yes:
            self.db.save_user(self.username, self.age, self.gender, self.occupation, preferences)
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setWindowTitle("User successfully created")
            msg.setText("New user registered with ID {}".format(len(self.db.users_dic)))
            msg.setStandardButtons(QMessageBox.Ok)
            res = msg.exec_()
            NewUserPreferencesWidget.close()
        else :
            pass
        #NewUserPreferencesWidget.close()

    def cancel_button_clicked(self, NewUserPreferencesWidget):
        NewUserPreferencesWidget.close()

    def retranslateUi(self, NewUserPreferencesWidget):
        _translate = QtCore.QCoreApplication.translate
        NewUserPreferencesWidget.setWindowTitle(_translate("NewUserPreferencesWidget", "Select user preferences"))
        self.label.setText(_translate("NewUserPreferencesWidget", "Give a value between 0 (not insterested) and 10 (very interested) for every genre:"))
        self.actionLabel.setText(_translate("NewUserPreferencesWidget", "Action"))
        self.actionValue.setText(_translate("NewUserPreferencesWidget", "0"))
        self.adventureLabel.setText(_translate("NewUserPreferencesWidget", "Adventure"))
        self.adventureValue.setText(_translate("NewUserPreferencesWidget", "0"))
        self.animationLabel.setText(_translate("NewUserPreferencesWidget", "Animation"))
        self.animationValue.setText(_translate("NewUserPreferencesWidget", "0"))
        self.childrensLabel.setText(_translate("NewUserPreferencesWidget", "Children\'s"))
        self.childrensValue.setText(_translate("NewUserPreferencesWidget", "0"))
        self.comedyLabel.setText(_translate("NewUserPreferencesWidget", "Comedy"))
        self.comedyValue.setText(_translate("NewUserPreferencesWidget", "0"))
        self.crimeLabel.setText(_translate("NewUserPreferencesWidget", "Crime"))
        self.crimeValue.setText(_translate("NewUserPreferencesWidget", "0"))
        self.documentaryLabel.setText(_translate("NewUserPreferencesWidget", "Documentary"))
        self.documentaryValue.setText(_translate("NewUserPreferencesWidget", "0"))
        self.dramaLabel.setText(_translate("NewUserPreferencesWidget", "Drama"))
        self.dramaValue.setText(_translate("NewUserPreferencesWidget", "0"))
        self.fantasyLabel.setText(_translate("NewUserPreferencesWidget", "Fantasy"))
        self.fantasyValue.setText(_translate("NewUserPreferencesWidget", "0"))
        self.filmnoirLabel.setText(_translate("NewUserPreferencesWidget", "Film-Noir"))
        self.filmnoirValue.setText(_translate("NewUserPreferencesWidget", "0"))
        self.horrorLabel.setText(_translate("NewUserPreferencesWidget", "Horror"))
        self.horrorValue.setText(_translate("NewUserPreferencesWidget", "0"))
        self.musicalLabel.setText(_translate("NewUserPreferencesWidget", "Musical"))
        self.musicalValue.setText(_translate("NewUserPreferencesWidget", "0"))
        self.mysteryLabel.setText(_translate("NewUserPreferencesWidget", "Mystery"))
        self.mysteryValue.setText(_translate("NewUserPreferencesWidget", "0"))
        self.romanceLabel.setText(_translate("NewUserPreferencesWidget", "Romance"))
        self.romanceValue.setText(_translate("NewUserPreferencesWidget", "0"))
        self.scifiLabel.setText(_translate("NewUserPreferencesWidget", "Sci-Fi"))
        self.scifiValue.setText(_translate("NewUserPreferencesWidget", "0"))
        self.thrillerLabel.setText(_translate("NewUserPreferencesWidget", "Thriller"))
        self.thrillerValue.setText(_translate("NewUserPreferencesWidget", "0"))
        self.warLabel.setText(_translate("NewUserPreferencesWidget", "War"))
        self.warValue.setText(_translate("NewUserPreferencesWidget", "0"))
        self.westernLabel.setText(_translate("NewUserPreferencesWidget", "Western"))
        self.westernValue.setText(_translate("NewUserPreferencesWidget", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewUserPreferencesWidget = QtWidgets.QWidget()
    ui = Ui_NewUserPreferencesWidget()
    ui.setupUi(NewUserPreferencesWidget)
    NewUserPreferencesWidget.show()
    sys.exit(app.exec_())
